[package]
name = "dioxus-qonversion"
version = "0.1.0"
edition = "2021"
description = "Unofficial Qonversion primitives for Dioxus mobile"
license = "MIT OR Apache-2.0"
readme = "./README.md"
homepage = "https://github.com/nichmorgan/dioxus-qonversion"
repository = "https://github.com/nichmorgan/dioxus-qonversion"
keywords = ["dioxus", "qonversion", "subscriptions", "mobile"]
categories = ["gui"]

[dependencies]
dioxus-lib = { version = "0.6", default-features = false, features = ["macro", "hooks", "signals"] }

[dev-dependencies]
dioxus = { version = "0.6", features = ["desktop"] }
